### ISSUE TITLE
Migrate to .NET Core

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.EsLint#6]
Addin should support .NET Core and Cake CoreCLR runner

**Comment by t-johnson** [comment]
I can take this on.  are you aiming to target .net standard 1.6 or 2.0 ?

**Comment by pascalberger** [comment]
@t-johnson Thanks, this would be great.

Same instructions as for https://github.com/cake-contrib/Cake.Issues/issues/4#issuecomment-336357489. But additionally Costura.Fody won't work with .NET Core, so we need to find another solution how to embed referenced assemblies which works with .NET Core.

**Comment by t-johnson** [comment]
How much of a pain is it to not have Costura.Fody?  it seems like this library will never be ported to .net core

**Comment by pascalberger** [comment]
@t-johnson We need to have the referenced assemblies (Newtonsoft.JSON) embedded to avoid running into version conflicts with other Cake addins. Since Costura.Fody doesn't support .NET Core we need to find another tool which works (ILMerge, ILRepack, ...). While Costura.Fody was very easy to implement, by just having to add a NuGet packages, which added the required MSBuild targets, tools like ILMerge or ILRepack need to be called from the build script. This requires either support in Cake.Recipe (see https://github.com/cake-contrib/Cake.Recipe/issues/61), or implementation in `setup.cake` throgh one of the extension points (the first one prefered in the long term to have the functionality reusable for other repos, but IMHO it would be fine to start with an implementation in the `setup.cake` file).

As far as I know there currently is no other Cake addin which does something like this (beside using Costura.Fody). 

@gep13 Do you have any other idea?

**Comment by t-johnson** [comment]
@pascalberger 
I did find there is an open issue for Costura to support .net standard 2.0 ([Fody/Costura/issues/227](https://github.com/Fody/Costura/issues/227)) and perhaps this would be easier for the long-term.  however it would mean that the target for all these addins that need it would require changing to .net standard 2.0.  Lots of dependencies in the chain here...

Other than embedding assemblies, or ILMerge, are there no other options for isolating these addins?  
I think i might tackle some other addins that don't have this problem in the meantime!

**Comment by t-johnson** [comment]
@pascalberger  Okay.  I think i will need the Cake.Issues nuget released with the .net standard 1.6 support to get a clean build of other Cake.Issues addins?

**Comment by pascalberger** [comment]
@t-johnson [Cake.Issues 0.2.0-beta0001](https://www.nuget.org/packages/Cake.Issues/0.2.0-beta0001) has been released including support for .NET Standard 1.6

**Comment by t-johnson** [comment]
@pascalberger 
Would you consider replacing the Newtonsoft.JSON dependancy with the standard System.Runtime.Serialization support for json?  may not be as performant or as nice, but at least its a dependancy-free solution?

**Comment by pascalberger** [comment]
@t-johnson Considering the lack of options for emebdding/merging the assemblies with .NET Core, removing dependencies by using standard classes is absolutely an option for me

**Comment by devlead** [comment]
If perf would be an issue and depending on what's being serialized you could also source code include a serializer like I've done with [Cake.MicrosoftTeams](https://github.com/cake-contrib/Cake.MicrosoftTeams/tree/master/src/Cake.MicrosoftTeams/LitJson).

**Comment by pascalberger** [comment]
@devlead Thanks!

IMHO perf is not that big of an issue for this kind of stuff, since normally you have just a single file to read, which also shouldn't be insanely big (otherwise you should maybe fix some things anyway 😃). So I'm OK to try with the out of the box stuff, to keep things simple, and if we see we run into perf issues or missing features we still can consider to add custom serializer to the addin.
